config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq'

  root 'alerts#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :groups do
    member do
      get 'new_members'
    end
  end

  resources :memberships
  
  resources :members do
    member do
      get 'new_groups'
    end
  end

  resources :users do
    member do
      put 'reset'
    end
  end

  resources :alerts

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships

  has_many :alert_groups, dependent: :destroy
  has_many :alerts, through: :alert_groups

  validates :name, presence: true
  validates :name, uniqueness: true

  def self.excludes(groups)
    where([" id not in (?)", groups])
  end

  def self.from_query(query)
    like = "%#{query}%"
    where([ "name LIKE ? OR description LIKE ? ", like, like ])
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.order('name').page(params[:page])
  end

  def new_members
    group = Group.find(params[:id])
    existing_members = group.members.map(&:id)

    members = Member.all
    members = members.excludes(existing_members) if existing_members.count > 0
    members = members.from_query(params[:q]) if params[:q].present?
    render json: members
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(filter_params)
    if @group.save
      redirect_to edit_group_path(@group), notice: 'Group has been created'
    else
      flash.now[:alert] = 'Failed to create group'
      render :new
    end
  end

  def edit
    @group = Group.includes(:memberships, :members).find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if(@group.update_attributes(filter_params))
      redirect_to groups_path, notice: 'Group has been updated'
    else
      flash.now[:alert] = 'Failed to update'
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if(@group.destroy)
      redirect_to groups_path, notice: 'Group has been deleted'
    else
      redirect_to groups_path, alert: "Failed to delete the group"
    end
  end

  private
  def filter_params
    params.require(:group).permit(:name, :description)
  end

end

app/views/groups/_form.html.erb
<%=simple_form_for(@group, html: { class: 'form-inline form'}) do |f| %>
  <%= errors_for @group %>
  <div class='input-row'>
    <%=f.input :name, input_html: {class: 'form-control'} %>
  </div>

  <div class='input-row'>
    <%=f.input :description, input_html: {class: 'form-control'} %>
  </div>
  
  <div class='input-row'>
    <label></label>
    <%=f.submit 'Save', label: false, class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/groups/_search_member.html.erb
<div>
  <div class="input-group">
    <input id='member-typeahead' type="text" 
          class="form-control typeahead" placeholder="Add Member"
          data-url="<%= new_members_group_path(@group) %>"

          >
    <span class="input-group-btn">
      <button id='add-member-group' class="btn btn-default" type="button">Add member</button>
    </span>
  </div>

  <input id='member-value' 
         type='hidden'
         value=''
         data-url='<%=memberships_path() %>'
         data-group-id='<%=@group.id %>'
         >
</div>

<br />

app/views/groups/edit.html.erb
<% content_for(:title) { "Edit User"} %>
<%= page_header "Edit Group" %>

<%= render 'form' %>

<div class='form-association'>
  <h4 class='sub-title'> Registering member </h4>
  <%= render 'search_member' %>

  <div id='member-list'>
    <%= render 'memberships/members', group: @group %>
  </div>
</div>

app/views/groups/index.html.erb
<%= paginate_for(@groups) %>
<%= page_header "List Group" do %>
  <%= link_to 'New Group', new_group_path() %>
<% end %>

<table class='table'>
  <thead>
    <tr>
      <td>Name</td>
      <td>Description</td>
      <td>Action</td>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, edit_group_path(group) %></td>
        <td><%= truncate(group.description) %></td>
        <td>
           <%= link_to "Delete", group_path(group), method: :delete, data: { confirm: 'Are you sure to delete this group' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate_for(@groups) %>

app/views/groups/new.html.erb
<% content_for(:title) { "New User"} %>
<%= page_header "Create a group" %>

<%= render 'form' %>