config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq'

  root 'alerts#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :groups do
    member do
      get 'new_members'
    end
  end

  resources :memberships
  
  resources :members do
    member do
      get 'new_groups'
    end
  end

  resources :users do
    member do
      put 'reset'
    end
  end

  resources :alerts

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  has_many :alert_groups, dependent: :destroy
  has_many :groups, through: :alert_groups

  has_many :alert_keywords, dependent: :destroy
  has_many :keywords, through: :alert_keywords

  has_many :alert_places, dependent: :destroy
  has_many :places, through: :alert_places

  has_many :feeds

  accepts_nested_attributes_for :alert_places, allow_destroy: true

  INTERVAL_UNIT_HOUR = "Hour"
  INTERVAL_UNIT_DAY  = "Day"

  INTERVAL_UNITS = [INTERVAL_UNIT_HOUR, INTERVAL_UNIT_DAY]

  validates :name, presence: true
  validates :url, presence: true
  validates :interval, presence: true, numericality: {greater_than: 0}
  validates :email_template, presence: true
  validates :sms_template, presence: true

end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController

  def index
    @alerts = Alert.order('created_at DESC').page(params[:page])
  end

  def new
    @alert = Alert.new
  end

  def create
    @alert = Alert.new(filter_params)

    if(@alert.save)
      redirect_to edit_alert_path(@alert), notice: 'Alert has been created'
    else
      flash.now[:alert] = 'Failed to create alert'
      render :new
    end
  end

  def edit
    @alert = Alert.find(params[:id])
  end

  def update
    @alert = Alert.find(params[:id])
    if(@alert.update_attributes(filter_params))
      redirect_to alerts_path, notice: 'Alert has been updated'
    else
      flash.now[:alert] = 'Could not save the alert'
      render :edit
    end
  end

  def destroy
    @alert = Alert.find(params[:id])
    if @alert.destroy
      redirect_to alerts_path, notice: 'Alert has been deleted'
    else
      redirect_to alerts_path, notice: 'Could not delete the alert'
    end
  end

  private
  def filter_params
    params.require(:alert).permit(:name, :url, :interval, :interval_unit, :email_template, :sms_template, 
                                  alert_places_attributes: [:id, :place_id, :_destroy],)
  end

end

app/views/alerts/_alert_groups.html.erb
<div id='alert-group' >
  <div class="input-group">
    <input type="text" 
          class="form-control typeahead" placeholder="Group"
          data-url="<%= new_groups_alert_path(@alert) %>" >

    <span class="input-group-btn">
      <%= link_to "Add Group", alert_alert_groups_path(@alert), class: 'btn btn-default typeahead-add' %>
    </span>
  </div>

  <input type='hidden' class='typeahead-value' >
</div>

app/views/alerts/_alert_keywords.html.erb
<div id='alert-keyword' >
  <div class="input-group">
    <input type="text" 
          class="form-control typeahead" placeholder="Keywords"
          data-url="<%= new_keywords_alert_path(@alert) %>" >

    <span class="input-group-btn">
      <%= link_to "Add Keywords", alert_alert_keywords_path(@alert), class: 'btn btn-default typeahead-add' %>
    </span>
  </div>

  <input type='hidden' class='typeahead-value' />

</div>


<table>
  <thead>
    <tr>
      <td>Keyword</td>
      <td></td>
    </tr>
  </thead>

  <tbody>
    
  </tbody>
</table>

app/views/alerts/_form.html.erb
<%= simple_form_for @alert, html: {class: 'form form-inline', id: 'form-alert'} do |f| %>
  <div class='input-row'>
    <%=f.input :name, input_html: {class: 'form-control'} %>
  </div>
  
  <div class='input-row'>
    <%=f.input :url, input_html: {class: 'form-control'} %>
  </div>

  <div class='input-row'>
    <%=f.input :interval, as: :string, input_html: {class: 'form-control inline-short'} %>
    <%=f.input :interval_unit, label: false, collection: Alert::INTERVAL_UNITS, include_blank: false,
               wrapper_html: { class: 'inline' }, input_html: {class: 'form-control'} %>
  </div>

  <div class='input-row'>
    <label style='display: table-cell;'> Places </label>
    <div class='row' style='display: table-cell;'>

      <% Place.order('name').all.each_with_index do |place,index| %>
        <div class='col-lg-6'>
          <% has_place = false %>

          <% @alert.alert_places.each do |alert_place| %>
            <% if place.id == alert_place.place_id %>
                <%= hidden_field_tag "alert[alert_places_attributes][#{index}][id]", alert_place.id %>
                <%= check_box_tag "alert[alert_places_attributes][#{index}][_destroy]", 1, false, class: 'hidden destroyable-alert-place' %>
                <%= check_box_tag "alert[alert_places_attributes][#{index}][place_id]", place.id, true, 
                                  class: 'mark-place', id: "alert_place_place_#{index}", class: 'marked-place' %>
                <label for='<%="alert_place_place_#{index}" %>'><%= place.name %></label>
                <% has_place = true %>
            <% end %>
          <% end %>

          <% if !has_place %>
            <%= check_box_tag "alert[alert_places_attributes][#{index}][place_id]", place.id, false,
                                  class: 'mark-place', id: "alert_place_place_#{index}" %>
            <label for='<%="alert_place_place_#{index}" %>'><%= place.name %></label>
          <% end %>

        </div>

      <% end %>

    </div>
  </div>

  <div class='input-row'>
    <%=f.input :email_template, as: :text, input_html: {class: 'form-control', rows: 4, cols: 40} %>
  </div>

  <div class='input-row-close'>
    <label></label>
    <%=email_template_params_for(:alert_email_template) %>
  </div>

  <div class='input-row'>
    <%=f.input :sms_template, as: :text, input_html: {class: 'form-control', rows: 4, cols: 40} %>
  </div>

  <div class='input-row-close'>
    <label></label>
    <%=sms_template_params_for(:alert_sms_template) %>
  </div>

  <div class='input-row'>
    <label></label>
    <%=f.submit 'Save', class: 'btn btn-info', id: 'btn-alert-form' %>
  </div>

<% end %>

app/views/alerts/edit.html.erb
<% content_for(:title) { "Alert"} %>
<%= page_header "Edit alert" %>

<%= render 'form' %>

app/views/alerts/index.html.erb
<%= paginate_for(@alerts) %>

<%= page_header "List Alert" do %>
  <%= link_to 'New Alert', new_alert_path() %>
<% end %>


<table class='table'>
  <thead>
    <tr>
      <td>Name</td>
      <td>Url</td>
      <td>Keywords</td>
      <td>Action</td>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= link_to alert.name, edit_alert_path(alert) %></td>
        <td><%= alert.url %></td>
        <td><%= truncate(alert.keywords.map(&:name).join(",")) %></td>
        <td>
           <%= link_to "Delete", alert_path(alert), method: :delete, data: { confirm: 'Are you sure to delete this alert' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate_for(@alerts) %>

app/views/alerts/new.html.erb
<% content_for(:title) { "Alert"} %>
<%= page_header "Create an alert" %>

<%= render 'form' %>