config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq'

  root 'alerts#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :groups do
    member do
      get 'new_members'
    end
  end

  resources :memberships
  
  resources :members do
    member do
      get 'new_groups'
    end
  end

  resources :users do
    member do
      put 'reset'
    end
  end

  resources :alerts

end

app/views/layouts/_nav_bar.html.erb
<nav class='navbar navbar-fixed-top main-nav'>
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class='glyphicon glyphicon-align-justify'></span>
      </button>
      <%=link_to ENV['APP_NAME'], root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <% if current_user %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Alerts", alerts_path %> </li>
        <li><%= link_to "Members", members_path %></li>
        <li><%= link_to "Groups", groups_path %></li>
        <li><%= link_to "Users", users_path %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
             <%= current_user.user_name %> <span class="caret"> </span>
          </a>

          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Profile', sign_out_path(), method: :delete %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign out', sign_out_path(), method: :delete %></li>
            
          </ul>
        </li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Alert system" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class='container'>
      <%= render "layouts/nav_bar" %>
      <%= flash_messages %>
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Alert system" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class='container'>
      <div class='sign-in'> 
         <%= yield %>
      </div>
    </div>
    
    <%= javascript_include_tag "application" %>
  </body>
</html>