config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq'

  root 'alerts#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resources :groups do
    member do
      get 'new_members'
    end
  end

  resources :memberships
  
  resources :members do
    member do
      get 'new_groups'
    end
  end

  resources :users do
    member do
      put 'reset'
    end
  end

  resources :alerts

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :memberships, dependent: :destroy
  has_many :groups, through: :memberships

  validates :full_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true

  def self.excludes(members)
    where([" id not in (?)", members])
  end

  def self.from_query(query)
    like = "%#{query}%"
    where([ "full_name LIKE ? OR email LIKE ? OR phone LIKE ? ", like, like, like ])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.order('full_name')
    @members = @members.from_query(params[:q]) if params[:q]
    @members = @members.page(params[:page])
  end

  def new
    @member = Member.new
  end

  def new_groups
    member = Member.find(params[:id])
    existing_groups = member.groups.map(&:id)

    groups = Group.all
    groups = groups.excludes(existing_groups) if existing_groups.count > 0
    groups = groups.from_query(params[:q]) if params[:q].present?
    render json: groups
  end

  def create
    @member = Member.new(filter_params)
    if @member.save
      redirect_to edit_member_path(@member), notice: 'Member has been created'
    else
      flash.now[:alert] = 'Failed to create member'
      render :new
    end
  end

  def edit
    @member = Member.includes(:memberships, :groups).find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if(@member.update_attributes(filter_params))
      redirect_to members_path, notice: 'Member has been updated'
    else
      flash.now[:alert] = 'Failed to update'
      render :edit
    end
  end

  def destroy
    @member = Member.find(params[:id])
    if(@member.destroy)
      redirect_to members_path, notice: 'Member has been deleted'
    else
      redirect_to members_path, alert: "Failed to delete the member"
    end
  end

  private
  def filter_params
    params.require(:member).permit(:full_name, :email, :phone, :email_alert, :sms_alert)
  end

end

app/views/members/_form.html.erb
<%=simple_form_for(@member, html: { class: 'form-inline form'}) do |f| %>
  <%= errors_for @member %>

  <div class='input-row'>
    <%=f.input :full_name, input_html: {class: 'form-control'} %>
  </div>

  <div class='input-row'>
    <%=f.input :email, input_html: {class: 'form-control'}, wrapper_html: { class: 'inline'} %>
    <%=f.input :email_alert, label: 'Email Alert', input_html: {class: 'form-control input-inline'}, wrapper_html: { class: 'inline'} %>
  </div>

  <div class='input-row'>
    <%=f.input :phone, label: 'Number', input_html: {class: 'form-control'}, wrapper_html: { class: 'inline'} %>
    <%=f.input :sms_alert, label: 'SMS Alert', input_html: {class: 'form-control input-inline'}, wrapper_html: { class: 'inline'} %>
  </div>


  <div class='input-row'>
    <label></label>
    <%=f.submit 'Save', label: false, class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/members/_search_group.html.erb
<div>
  <div class="input-group">
    <input id='group-typeahead' type="text" 
          class="form-control typeahead" placeholder="Add Group"
          data-url="<%= new_groups_member_path(@member) %>"

          >
    <span class="input-group-btn">
      <button id='add-group' class="btn btn-default" type="button">Add Group</button>
    </span>
  </div>

  <input id='group-value' 
         type='hidden'
         value=''
         data-url='<%=memberships_path() %>'
         data-member-id='<%=@member.id %>'
         >
</div>

<br />

app/views/members/edit.html.erb
<% content_for(:title) { "Edit Member"} %>
<%= page_header "Edit Member" %>

<%= render 'form' %>

<div class='form-association'>
  <h4 class='sub-title'> Registering groups</h4>
  <%= render 'search_group' %>

  <div id='group-list'>
    <%= render 'memberships/groups', member: @member %>
  </div>
</div>

app/views/members/index.html.erb
<%= paginate_for(@members) %>
<%= page_header "List Member" do %>
  <%= link_to 'New Member', new_member_path() %>
<% end %>

<table class='table'>
  <thead>
    <tr>
      <td>Full Name</td>
      <td>Email</td>
      <td>Number</td>
      <td>Email Alert</td>
      <td>SMS Alert</td>
      <td>Action</td>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.full_name, edit_member_path(member) %></td>
        <td><%=member.email %></td>
        <td><%=member.phone %></td>
        <td><%=member.email_alert %></td>
        <td><%=member.sms_alert %></td>
        <td>
           <%= link_to "Delete", member_path(member), method: :delete, data: { confirm: 'Are you sure to delete this member' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate_for(@members) %>

app/views/members/new.html.erb
<% content_for(:title) { "New User"} %>
<%= page_header "Create a member" %>

<%= render 'form' %>